version: 2.1
orbs:
  aws-s3: circleci/aws-s3@1.0.15
jobs:
  test:
    docker:
      - image: djum17/us_schools_ui:latest
    steps:
      - run: npm install
      - run: npm run test
  build:
    docker:
      - image: djum17/us_schools_ui:latest
    steps:
      - run: npm run build
  deploy:
    docker:
      - image: djum17/us_schools_ui:latest
    steps:
      - run: sudo apt-get update && sudo apt-get install -y python-dev
      - run: sudo curl -O https://bootstrap.pypa.io/get-pip.py
      - run: sudo python get-pip.py
      - run: sudo pip install awscli --upgrade
      - run: aws --version
      - run: aws s3 ls
      - run: npm run deploy

workflows:
    test-build-deploy:
      jobs:
        - test
        - build
        - deploy:
            requires:
              - build